#Exception
number1=int(input("ป้อนตัวเลขที่ 1:"))
number2=int(input("ป้อนตัวเลขที่ 2:"))

result = number1/number2
print("ผลลัพธ์ = ",result)